import { ApiProperty } from '@nestjs/swagger';

export class GenericErrorResponse {
    @ApiProperty({
        description: 'The associated status code of the error',
        example: 404,
    })
    readonly statusCode: number;

    @ApiProperty({
        description: 'Name of the error',
        example: 'Not found',
    })
    readonly error: string;

    @ApiProperty({
        description: 'The associated message of the error, either generated by the connector, or the CMS behind the request',
        example: 'The resource you were looking for was not found',
    })
    readonly message: string;
}